#!/usr/bin/env node
// Keeps relative-import specifiers uniform per resolution zone (#9221). The repo compiles two ways, and the
// correct specifier style follows the IMPORTING file's own zone -- not its target, and not whether the
// target happens to live under packages/**:
//
//   • src/**, scripts/**, test/** -- root tsconfig, `moduleResolution: "Bundler"`. Bundler resolution reads
//     extensionless specifiers directly (vitest/tsc read a package's .ts SOURCE here, never its built dist),
//     and tsx (which runs every scripts/** CLI) resolves them too. Verified directly: an extensionless
//     relative import into packages/loopover-engine/src resolves and type-checks fine from this zone.
//     EXTENSIONLESS is the single style. `src/**` already used it; `scripts/**` and `test/**` had drifted to
//     `.js`, including on imports that reach into packages/** source.
//   • packages/** -- their own tsconfigs, `moduleResolution: "NodeNext"`, PUBLISHED as real ESM. A file
//     INSIDE a NodeNext package importing another file inside ITS OWN package must keep `.js`: Node's ESM
//     resolver requires the emitted extension there, and that is a hard constraint of shipping ESM, not a
//     style choice. This only applies to a package's own internal imports -- once anything from `src/**`,
//     `scripts/**`, or `test/**` reaches INTO a package, the importer's Bundler zone rule applies instead.
//
// `.ts` specifiers are rejected everywhere: the root tsconfig does not set `allowImportingTsExtensions`, so
// they fail typecheck (TS5097) rather than merely looking inconsistent.
import { readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";

const BUNDLER_ROOTS = ["src", "scripts", "test"] as const;
const NODENEXT_ROOTS = ["packages"] as const;
// Excludes .d.ts: generated/ambient declaration files (worker-configuration.d.ts et al.) are not authored
// import sites and are regenerated by their own drift check (cf-typegen:check), not this one.
const SOURCE_PATTERN = /(?<!\.d)\.tsx?$/;
const EXCLUDED_SEGMENT = /(?:^|\/)(?:node_modules|dist|dist-test)(?:\/|$)/;
/** This checker's OWN test file deliberately embeds import-statement TEXT as string fixtures (to feed the
 *  injectable `readFile`), not real imports of its own -- scanning it as source would flag its fixtures as
 *  violations of themselves. Mirrors check-coverage-bolt-on-filenames.ts's own ALLOWED_FILENAMES pattern for
 *  the same class of self-referential false positive. */
const ALLOWED_FILENAMES = new Set(["check-import-specifiers-script.test.ts"]);
/** A relative specifier in an import/export/dynamic-import, with its optional `.js`/`.ts`/`.d.ts` extension
 *  captured separately from the rest of the path -- anything else (`.json`, `.css`, no extension at all)
 *  matches the base-path group instead and is never flagged or rewritten. `.d.ts` must be tried before the
 *  bare `.ts` alternative, or a `claim-ledger.d.ts` declaration-only import (a real, separate, always-valid
 *  form pairing with a sibling `.js` runtime import) would have its trailing `.ts` misread as the generic
 *  banned extension. */
const SPECIFIER_PATTERN = /(?:from|import)\s*\(?\s*"((?:\.{1,2}\/)[^"]+?)(\.d\.ts|\.js|\.ts)?"/g;
/** A base path ending in any OTHER dot-extension (`.json`, `.css`, `.svg`, ...) is not a bare module
 *  specifier -- e.g. `../package.json` under an import-assertion (`with { type: "json" }`). Neither
 *  resolution rule applies to it: it needs no `.js` under NodeNext, and isn't a `.js` violation under
 *  Bundler (it was never captured as one, since the extension group only matches `.d.ts`/`.js`/`.ts`). */
const OTHER_EXTENSION_TAIL = /\.[A-Za-z0-9]+$/;

export type ImportSpecifierViolation = { file: string; specifier: string; reason: string };

function defaultListSourceFiles(root: string): string[] {
  try {
    return readdirSync(root, { recursive: true })
      .map(String)
      .filter((entry) => SOURCE_PATTERN.test(entry) && !EXCLUDED_SEGMENT.test(entry))
      .map((entry) => `${root}/${entry}`);
  } catch {
    // A root that doesn't exist in a given checkout is not a violation -- report nothing for it.
    return [];
  }
}

/** Pure over its inputs: scans each zone's files for relative-import specifiers and checks the extension
 *  against that ZONE's rule (not the target's). `listSourceFiles`/`readFile` are injectable so tests can
 *  simulate offenders without writing into the real tree. */
export function findImportSpecifierViolations(
  options: {
    bundlerRoots?: readonly string[];
    nodeNextRoots?: readonly string[];
    listSourceFiles?: (root: string) => string[];
    readFile?: (file: string) => string;
  } = {},
): ImportSpecifierViolation[] {
  const {
    bundlerRoots = BUNDLER_ROOTS,
    nodeNextRoots = NODENEXT_ROOTS,
    listSourceFiles = defaultListSourceFiles,
    readFile = (file: string) => readFileSync(file, "utf8"),
  } = options;

  const violations: ImportSpecifierViolation[] = [];
  const scan = (root: string, zone: "bundler" | "nodenext"): void => {
    for (const file of listSourceFiles(root)) {
      if (ALLOWED_FILENAMES.has(file.split("/").pop() ?? file)) continue;
      for (const match of readFile(file).matchAll(SPECIFIER_PATTERN)) {
        const specifier = match[1] ?? "";
        const extension = match[2] ?? "";
        const full = `${specifier}${extension}`;

        if (extension === ".d.ts") {
          // A declaration-only import of a package's own type file is always valid, in either zone -- it is
          // not a runtime module specifier subject to either resolution rule.
          continue;
        }
        if (extension === ".ts") {
          violations.push({ file, specifier: full, reason: "`.ts` specifiers fail typecheck (TS5097)" });
        } else if (zone === "bundler" && extension === ".js") {
          violations.push({ file, specifier: full, reason: "this file's zone (src/scripts/test) resolves extensionless under Bundler" });
        } else if (zone === "nodenext" && extension !== ".js" && !OTHER_EXTENSION_TAIL.test(specifier)) {
          violations.push({ file, specifier: full, reason: "this file's own package is NodeNext-resolved ESM and requires `.js`" });
        }
      }
    }
  };
  for (const root of bundlerRoots) scan(root, "bundler");
  for (const root of nodeNextRoots) scan(root, "nodenext");
  return violations.sort((a, b) => (a.file === b.file ? a.specifier.localeCompare(b.specifier) : a.file.localeCompare(b.file)));
}

function main(): void {
  const violations = findImportSpecifierViolations();
  if (violations.length === 0) {
    process.stdout.write("import specifiers: OK\n");
    return;
  }
  process.stderr.write(`Found ${violations.length} import-specifier violation(s) (#9221):\n`);
  for (const violation of violations) {
    process.stderr.write(`  ${violation.file}: "${violation.specifier}" — ${violation.reason}\n`);
  }
  process.exit(1);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
