#!/usr/bin/env node
// Generate every MCP tool-reference surface from the contract registry (#9521).
//
// One row set -> four surfaces, the same one-source pattern gen-selfhost-env-reference.ts and
// gen-command-reference.ts already established (the latter's header records why: "a hand-copy is
// exactly how the 9-command queue-digest family went completely undocumented"). Before this, the
// stdio README told users to run `loopover-mcp tools` instead of documenting anything, the miner
// README hand-kept a 12-bullet prose list, and 32 tool names sat in apps/loopover-ui/content/docs
// with no drift check at all.
//
// Surfaces:
//   1. packages/loopover-mcp/README.md   -- tool table between the GENERATED:MCP-TOOLS markers
//   2. packages/loopover-miner/README.md -- tool table between the same markers
//   3. apps/loopover-ui/src/lib/mcp-tool-reference.ts -- typed module for the docs site
//
// `--check` regenerates in memory and diffs, exiting 1 on drift; test:ci runs it. The docs-drift
// side (every loopover_* name mentioned under content/docs exists in the registry) lives in
// scripts/check-docs-drift.ts, which already owns that class of check.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { LEGACY_MCP_TELEMETRY_PROPERTY_KEYS, listToolDefinitions, type McpToolDefinition } from "@loopover/contract";
import { STDIO_TOOL_NAMES } from "../packages/loopover-mcp/bin/loopover-mcp";

const CHECK = process.argv.includes("--check");
const ROOT = process.cwd();

const BEGIN = "<!-- GENERATED:MCP-TOOLS:BEGIN — edit the @loopover/contract registry, then `npm run mcp:tool-reference` -->";
const END = "<!-- GENERATED:MCP-TOOLS:END -->";
const TELEMETRY_BEGIN = "<!-- GENERATED:MCP-TELEMETRY-PROPS:BEGIN — edit LEGACY_MCP_TELEMETRY_PROPERTY_KEYS in @loopover/contract, then `npm run mcp:tool-reference` -->";
const TELEMETRY_END = "<!-- GENERATED:MCP-TELEMETRY-PROPS:END -->";

/** The README's telemetry property table, from the same constant both telemetry modules build the
 *  event through -- so the prose can no longer promise a different field set than the code sends. */
const TELEMETRY_PROPERTY_NOTES: Record<(typeof LEGACY_MCP_TELEMETRY_PROPERTY_KEYS)[number], { example: string; note: string }> = {
  tool: { example: "`predict_gate`", note: "The MCP tool name." },
  caller_type: { example: "`local`", note: "Which surface dispatched it (`local` for this CLI)." },
  ok: { example: "`true`", note: "Whether the call succeeded." },
  duration_ms: { example: "`142`", note: "Coarse wall-clock duration." },
};

function telemetryTable(): string {
  const lines = ["| Field | Example | What it is |", "| --- | --- | --- |"];
  for (const key of LEGACY_MCP_TELEMETRY_PROPERTY_KEYS) {
    const meta = TELEMETRY_PROPERTY_NOTES[key];
    lines.push(`| \`${key}\` | ${meta.example} | ${meta.note} |`);
  }
  return lines.join("\n");
}

function replaceTelemetrySection(source: string): string {
  const begin = source.indexOf(TELEMETRY_BEGIN);
  const end = source.indexOf(TELEMETRY_END);
  if (begin === -1 || end === -1) throw new Error("packages/loopover-mcp/README.md is missing the GENERATED:MCP-TELEMETRY-PROPS markers.");
  return source.slice(0, begin + TELEMETRY_BEGIN.length) + "\n" + telemetryTable() + "\n" + source.slice(end);
}

/** One markdown table for a set of tools, grouped by category in a stable order. */
function toolTable(tools: readonly McpToolDefinition[]): string {
  const categories = [...new Set(tools.map((tool) => tool.category))].sort();
  const lines: string[] = [];
  for (const category of categories) {
    lines.push(`\n#### ${category}\n`);
    lines.push("| Tool | Description |");
    lines.push("| --- | --- |");
    for (const tool of tools.filter((entry) => entry.category === category).sort((a, b) => a.name.localeCompare(b.name))) {
      // Pipes would break the table; the registry has none today, but a future description must not
      // be able to corrupt the file it is rendered into.
      const description = tool.description.replace(/\|/g, "\\|").replace(/\n/g, " ");
      lines.push(`| \`${tool.name}\` | ${description} |`);
    }
  }
  return lines.join("\n");
}

function replaceBetweenMarkers(source: string, replacement: string, file: string): string {
  const begin = source.indexOf(BEGIN);
  const end = source.indexOf(END);
  if (begin === -1 || end === -1) throw new Error(`${file} is missing the GENERATED:MCP-TOOLS markers.`);
  return source.slice(0, begin + BEGIN.length) + "\n" + replacement + "\n" + source.slice(end);
}

function uiModule(tools: readonly McpToolDefinition[]): string {
  const rows = tools
    .map((tool) => ({ name: tool.name, category: tool.category, locality: tool.locality, availability: tool.availability, description: tool.description }))
    .sort((a, b) => a.name.localeCompare(b.name));
  return `// GENERATED by scripts/gen-mcp-tool-reference.ts from the @loopover/contract registry (#9521).
// Do not edit by hand; run \`npm run mcp:tool-reference\`.

export type McpToolReferenceEntry = {
  name: string;
  category: string;
  locality: "remote" | "local-git" | "miner";
  availability: "cloud" | "selfhost" | "both";
  description: string;
};

export const MCP_TOOL_REFERENCE: readonly McpToolReferenceEntry[] = ${JSON.stringify(rows, null, 2)};
`;
}

function main(): void {
  const all = listToolDefinitions();
  const stdioNames = new Set<string>(STDIO_TOOL_NAMES);
  const targets: Array<{ file: string; next: (current: string) => string }> = [
    {
      file: "packages/loopover-mcp/README.md",
      next: (current) =>
        replaceTelemetrySection(replaceBetweenMarkers(current, toolTable(all.filter((tool) => stdioNames.has(tool.name))), "packages/loopover-mcp/README.md")),
    },
    {
      file: "packages/loopover-miner/README.md",
      next: (current) => replaceBetweenMarkers(current, toolTable(all.filter((tool) => tool.locality === "miner")), "packages/loopover-miner/README.md"),
    },
    {
      file: "apps/loopover-ui/src/lib/mcp-tool-reference.ts",
      next: () => uiModule(all),
    },
  ];

  const drifted: string[] = [];
  for (const target of targets) {
    const path = join(ROOT, target.file);
    let current = "";
    try {
      current = readFileSync(path, "utf8");
    } catch {
      // A missing UI module is simply generated fresh; a missing README is a real error surfaced by
      // the marker check inside next().
    }
    const next = target.next(current);
    if (next === current) continue;
    if (CHECK) drifted.push(target.file);
    else writeFileSync(path, next);
  }

  if (CHECK && drifted.length > 0) {
    process.stderr.write(`gen-mcp-tool-reference: stale generated output in ${drifted.join(", ")} -- run \`npm run mcp:tool-reference\`.\n`);
    process.exit(1);
  }
  process.stdout.write(`gen-mcp-tool-reference: ${CHECK ? "checked" : "wrote"} ${targets.length} surface(s) from ${all.length} registry entries.\n`);
}

main();
