#!/usr/bin/env node
// Mirrors packages/loopover-contract/src/control-plane.ts into control-plane/src/generated/ (#9750).
//
// Why a generated mirror rather than a dependency: `control-plane/` is NOT an npm workspace member. It
// carries its own package-lock.json and CI installs it separately (`npm run control-plane:install`), so a
// `file:` edge onto @loopover/contract would require that package to be BUILT before that install runs --
// an ordering constraint across two independent installs, for one zod-only module.
//
// The mirror is byte-identical apart from a header, and `--check` runs in test:ci, so the copy cannot
// diverge from the source. Same posture as gen-contract-api-schemas.ts, which mirrors in the other
// direction for the same class of reason: a package that cannot import a source still needs its schemas.
//
// The contract module is the canonical one. Editing the generated file is the thing this check exists to
// catch -- and it will, on the very next CI run.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { pathToFileURL } from "node:url";

const SOURCE = "packages/loopover-contract/src/control-plane.ts";
const TARGET = "control-plane/src/generated/control-plane-contract.ts";

const HEADER = `// GENERATED by scripts/gen-control-plane-contract.ts from ${SOURCE} (#9750).
// Do not edit by hand; edit the contract module and run \`npm run control-plane:contract\`.
//
// control-plane/ is not an npm workspace member, so it cannot import @loopover/contract directly. This
// mirror is what lets the Worker validate against the SAME schemas the published spec is generated from
// and the miner's admin client parses with.

`;

export function render(source: string): string {
  return HEADER + source;
}

function main(argv: readonly string[]): void {
  const check = argv.includes("--check");
  const root = process.cwd();
  const next = render(readFileSync(join(root, SOURCE), "utf8"));
  const path = join(root, TARGET);

  let current = "";
  try {
    current = readFileSync(path, "utf8");
  } catch {
    // A missing mirror is generated fresh; under --check it is drift like any other.
  }

  if (next === current) {
    process.stdout.write(`gen-control-plane-contract: ${TARGET} is up to date.\n`);
    return;
  }
  if (check) {
    process.stderr.write(`gen-control-plane-contract: ${TARGET} is stale -- run \`npm run control-plane:contract\`.\n`);
    process.exit(1);
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, next);
  process.stdout.write(`gen-control-plane-contract: wrote ${TARGET}.\n`);
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) main(process.argv.slice(2));
