// Which routes require a credential, as ONE model (#9531).
//
// Extracted from src/api/routes.ts so the OpenAPI builder can read the same predicate the app gates
// on. It cannot import routes.ts: that module reaches `cloudflare:` imports, and the spec is
// generated by a plain Node script (scripts/write-ui-openapi.ts) whose loader cannot resolve them.
//
// Before this, src/openapi/spec.ts carried `isProtectedPath` -- a second, path-prefix approximation
// that treated every `/v1/*` route as protected bar a short literal list. It had already drifted:
// the whole `/v1/public/decision-ledger/*` family answers 200 to an anonymous caller and was
// published as needing a bearer. A pure module both sides import is what makes that class of drift
// impossible rather than merely fixed.
//
// PURE by construction: string predicates only, no env, no I/O, no Workers types. Keep it that way
// -- the moment this file needs a runtime binding, the spec builder stops working again.

/**
 * The ONE model of which routes are credential-gated (#9531).
 *
 * Exported so src/openapi/spec.ts derives its security stanzas from this rather than from a second,
 * path-prefix approximation of it. `isProtectedPath` was that approximation, and it had already
 * drifted: it treated every `/v1/*` path as protected except a short literal list, which disagreed
 * with this function on the whole `/v1/public/decision-ledger/*` family among others -- so the
 * published document advertised a bearer requirement on routes that answer 200 to an anonymous
 * caller. Deriving from the enforcer means the document cannot say something the middleware does
 * not do.
 */
export function requiresApiToken(path: string): boolean {
  if (path === "/health") return false;
  if (path === "/v1/mcp/compatibility") return false;
  if (path === "/v1/mcp/finding-taxonomy") return false;
  if (path === "/v1/mcp/enrichment-analyzers") return false;
  if (/^\/v1\/public\/github\/repos\/[^/]+\/[^/]+\/stats$/.test(path)) return false;
  if (/^\/v1\/public\/repos\/[^/]+\/[^/]+\/badge\.(svg|json)$/.test(path)) return false;
  if (/^\/v1\/public\/repos\/[^/]+\/[^/]+\/quality$/.test(path)) return false;
  if (path === "/v1/public/subnet-interface") return false;
  if (path === "/v1/public/stats") return false;
  // #9120: this route's own doc comment always claimed "safe unauthenticated" but was missing from this exact
  // list, so it 401'd in prod — verified live: subnet-interface/stats/quality answered 200, this one 401'd.
  if (path === "/v1/public/decision-ledger/verify") return false;
  // #9266: the eval-scores transport is unauthenticated by the same design as every /v1/public/* sibling
  // above -- committed to a corpus checksum, independently re-derivable, nothing gated behind a token.
  if (path === "/v1/public/eval-scores") return false;
  // #9269: the single-row read, added in the SAME PR as its route so the two can never drift the way #9120's
  // sibling did. Regex (not a literal) because of the :seq path parameter.
  if (/^\/v1\/public\/decision-ledger\/row\/[^/]+$/.test(path)) return false;
  // #9270: the published anchor-signing public keys, added in the SAME PR as its route so the two cannot
  // drift the way #9120's sibling did.
  if (path === "/v1/public/decision-ledger/anchor-key") return false;
  // #9271: the public anchor-attempt listing, added in the SAME PR as its route.
  if (path === "/v1/public/decision-ledger/anchors") return false;
  // #9569: the public proof page's data and its README badge. Unauthenticated by design -- every figure
  // they render is already served unauthenticated by the ledger-verify / anchors / decision-record routes
  // above; this is a composition, not a new disclosure. Added in the SAME PR as the routes, per #9120.
  if (/^\/v1\/public\/repos\/[^/]+\/[^/]+\/proof$/.test(path)) return false;
  if (/^\/v1\/public\/repos\/[^/]+\/[^/]+\/proof-badge\.svg$/.test(path)) return false;
  // #9277: the current tip's signed checkpoint, for the operator's off-Worker Bittensor submitter (and
  // anyone else — it is the same payload the Rekor/git backends already publish externally). Added in the
  // SAME PR as its route, per the #9120 lesson.
  if (path === "/v1/public/decision-ledger/anchor-payload") return false;
  // #9277: the submitter's report route carries its OWN bearer gate (isAuthorizedIngest against
  // LOOPOVER_LEDGER_ANCHOR_REPORT_TOKEN, fails closed when unset) — same posture as /v1/orb/ingest below.
  if (path === "/v1/decision-ledger/anchor-attempts") return false;
  // #9123: the new public decision-record read route — same unauthenticated posture as its ledger-verify
  // sibling immediately above, added in the SAME PR so the two can never drift apart the way #9120 did. The
  // pull segment matches any non-slash text (not just digits): an invalid pull number is the ROUTE's 400 to
  // return, not the auth gate's 401 — mirrors every other dynamic-segment exemption below (owner/repo use the
  // same unvalidated [^/]+).
  if (/^\/v1\/public\/decision-records\/[^/]+\/[^/]+\/[^/]+$/.test(path)) return false;
  if (path === "/openapi.json") return false;
  if (path === "/mcp") return false;
  // #9526: the MCP discovery surfaces. Every field they carry -- tool names, descriptions, and JSON
  // schemas -- is already public via /mcp's own tools/list and the published OpenAPI document, so gating
  // them would only stop a registry crawler from finding a server that advertises itself on purpose.
  if (path === "/.well-known/mcp.json" || path.startsWith("/.well-known/agent-tools/")) return false;
  // Public OAuth draft-submission flow (LOOPOVER_REVIEW_DRAFT): the submission entry points are unauthenticated
  // by design. The handlers themselves 404 when the flag is off, so this exemption is inert flag-OFF.
  if (path === "/v1/drafts" || path.startsWith("/v1/drafts/")) return false;
  if (path.startsWith("/v1/auth/")) return false;
  if (path === "/v1/github/webhook") return false;
  if (path === "/v1/orb/webhook") return false;
  if (path === "/v1/orb/relay") return false;
  if (path === "/v1/orb/oauth/callback") return false;
  if (path === "/v1/orb/token") return false;
  if (path === "/v1/orb/relay/register") return false;
  if (path === "/v1/orb/relay/pull") return false;
  if (path === "/v1/orb/ingest") return false;
  if (path === "/v1/ams/ingest") return false;
  if (path.startsWith("/v1/internal/")) return false;
  return path.startsWith("/v1/");
}
